alias ..='cd ..'
alias Desktop='cd ~/Desktop'
alias Downloads='cd ~/Downloads'
alias a-remove='sudo apt remove'
alias base='/home/hamza/PROJECTS/clang/base.c/base'
alias bashlang='cd /home/hamza/PROJECTS/bash/'
alias battery='acpi | awk '\''NR==2 {gsub(",", "");print $4}'\'''
alias c='clear'
alias clang='cd ~/PROJECTS/clang'
alias cpu='ps auxf | sort -nr -k 3 | head -5'
alias desktop='cd /mnt/c/Users/omira/OneDrive/Desktop/'
alias disk='df -h | awk '\''NR==3'\'''
alias download='yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
alias egrep='egrep --color=auto'
alias exa='exa --icons=always'
alias fgrep='fgrep --color=auto'
alias gccw='gcc -Wall -Wextra -Werror'
alias grep='grep --color=auto'
alias h='history'
alias install='sudo apt install'
alias ip='ifconfig | grep -w inet | awk '\''NR == 2 {print $2}'\'''
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lowercase='lowercaseText'
alias m='main'
alias n='nano *.js'
alias nd='node *.js'
alias o='cd ~/linux-commands && sudo nano learn'
alias of='cd ~/linux-commands/'
alias open='xdg-open'
alias own='/home/hamza/scripts/make'
alias purge='sudo apt purge'
alias quality0='bash ~/scripts/quality.sh'
alias quality1='bash ~/scripts/quality2.sh'
alias quality2='bash ~/scripts/quality4.sh'
alias quality3='bash ~/scripts/quality5.sh'
alias quality4='bash ~/scripts/quality6.sh'
alias quality5='bash ~/scripts/quality7.sh'
alias remove='sudo apt remove'
alias s='sudo'
alias s-remove='sudo snap remove'
alias screenshots='cd /home/hamza/Pictures/Screenshots/'
alias search='sudo apt search'
alias ser='python3 -m http.server 8000'
alias server='python3 -m http.server'
alias sinstall='sudo snap install'
alias sourcebash='source ~/.bashrc'
alias spurge='sudo snap remove --purge'
alias sremove='sudo snap remove --remove'
alias ss='sudo systemctl status'
alias ssearch='sudo snap search'
alias sst='sudo systemctl stop'
alias suspend='systemctl suspend'
alias t='touch'
alias terminal='powershell.exe /c start wsl'
alias tor='cd ~/.local/share/applications/ && env ./start-tor-browser.desktop && cd -'
alias typing='firefox typelit.io &'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias uppercase='uppercaseText'
alias v='vim'
alias vimbash='vim ~/.bashrc'
alias warp='warp-terminal'
alias x='exit'
alias yazi='~/Downloads/yazi/target/release/yazi'
alias youtube='brave youtube.com &'
alias yt='yt-dlp -f bestvideo+bestaudio'
alias sbash='source ~/.bashrc'
alias vbash='vim ~/.bashrc'
alias f='source ~/file.sh'
alias mk='mkdir'
alias rf='rm -rf'
alias hf='/home/hamza/scripts/hf/hf.sh'
alias bat='batcat'
alias shutdown='shutdown -P now'
alias iphone='ifuse ~/IPHONE --documents org.videolan.vlc-ios'
alias slist='snap list'
alias list='apt list'
alias q='exit'
alias autoremove='sudo apt autoremove && sudo apt autopurge && sudo apt autoclean'
alias notify='bash /media/hamza/7e00b547-68c0-4bf8-b059-1740573eb33c/home/hamza/PROJECTS/bash/pushover/file.sh'
alias md='mkdir'
alias desktop='cd ~/Desktop'
alias Desktop='cd ~/Desktop'
desktop="${HOME}/Desktop"
export desktop
alias valias='vim ~/.alias.sh'
alias script='bash ~/scripts/script.sh'
